In [1]:
# import the random module
import random

# use the module to create a random number
r = random.uniform(0, 100)
print(r)


58.765878248893785


In [2]:
# import the random module
import random as rnd

# use the module to create a random number
r = rnd.uniform(0, 100)
print(r)

88.50399107042004


In [3]:
from random import uniform
r = uniform(0,100)
print(r)

69.02344449398363


In [4]:
from random import uniform as urand
r = urand(0,100)
print(r)

55.69385525258149


In [5]:
# compare lists to np arrays

# list approach
squares = []
for n in range(10):
    squares.append(n*n)
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
# numpy approach
import numpy as np

v = np.array(range(10))
print(v)


[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(5 * v)

[ 0  5 10 15 20 25 30 35 40 45]


In [9]:
print(v * v)

[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
# convert from list to array
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [11]:
a_vector = np.array(a)
print(a_vector)

[1 2 3]


In [12]:
# convert a list of lists to a 2D array
a_matrix = np.array([a, a])
print(a_matrix)

[[1 2 3]
 [1 2 3]]


In [14]:
print(np.hstack([a, a]))

[1 2 3 1 2 3]


In [15]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b_matrix = np.array(b)
print(b_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(np.vstack([a, a]))

[[1 2 3]
 [1 2 3]]


In [17]:
c_list = range(20)
print(c_list)

range(0, 20)


In [18]:
c_vector = np.arange(20)

In [19]:
print(c_vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
print(np.ones(3)*10)

[10. 10. 10.]


In [24]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [25]:
print(np.arange(0, 10, 5))

[0 5]


In [27]:
print(np.arange(0, 12.5, 2.5))

[ 0.   2.5  5.   7.5 10. ]


In [28]:
# I == identity matrix
# all zeros except along the diagonal
# np.eye() generates an indentify matrix
print(np.eye(3)) # 3 by 3 identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
# create an empty array
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
# numpy also provides random numbers via np.random
# use random.rand() for uniform distribution on (0,1)
print(np.random.rand(5)) # a vector of 5 uniform random numbers

[0.57871876 0.86571555 0.87871404 0.45057542 0.09696289]


In [37]:
print(np.random.rand(3,3)) # a 3 by 3 matrix of uniform random numbers

[[0.82401696 0.99245275 0.72416101]
 [0.75525424 0.84126244 0.94163809]
 [0.77212743 0.52891263 0.92860558]]


In [38]:
# normal or Gaussian uses randn() with mean = 0, std. dev. = 1
print(np.random.randn(3))

[-0.61531053  0.41798627  1.43543807]


In [39]:
print(np.random.randn(3,3))

[[ 1.08939481  0.66814387  0.00539241]
 [-0.73847065  0.39091744  0.43520866]
 [-1.63300085 -1.05963535 -1.24707348]]


In [42]:
# if you want random integers, use randint() ... analogous to the random module
print(np.random.randint(1, 100))

92


In [43]:
# use third arg to get multiple samples
print(np.random.randint(1, 100, 5))

[94  5 79 15 77]


In [44]:
vector = np.arange(1,10)
print(vector)

[1 2 3 4 5 6 7 8 9]


In [45]:
print(vector.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
vector = np.arange(1,11)

In [47]:
print(vector.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
# the reshaped array must have same number of entries
print(vector.reshape(3,5))

ValueError: cannot reshape array of size 10 into shape (3,5)

In [50]:
# a vector of 25 random ints between 1 and 50
vector = np.random.randint(1,50,25)

In [51]:
# what's the smallest value?
print(vector.min())

2


In [52]:
# what's the largest?
print(vector.max())

48


In [53]:
# use argmin() and argmax() to get the corresponding indices
print(vector.argmin())


16


In [55]:
print(vector[16])

2


In [56]:
print(vector.argmax())

6


In [57]:
print(vector[6])

48


In [58]:
# query the dimensions (aka the shape)
print(vector.shape)

(25,)


In [59]:
a2 = vector.reshape(5,5)

In [60]:
print(a2.shape)

(5, 5)


In [61]:
# use square brackets for indexing, and slicing is supported
# just elements 3-7 (or 3-8, non-inclusive)
print(vector[3:8])

[43 33 18 48 35]


In [62]:
print(vector[:5])

[23 28 35 43 33]


In [63]:
print(vector[0:5])

[23 28 35 43 33]


In [64]:
print(vector[20:])

[ 9 34 31 42 33]


In [65]:
# third value provides the step
print(vector[3:9:2])

[43 18 35]


In [66]:
# last element
print(vector[-1])

33


In [67]:
# 2nd from last element
print(vector[-2])

42


In [68]:
print(vector[3:6])

[43 33 18]


In [69]:
vector[3:6] = 12

In [70]:
print(vector[3:6])

[12 12 12]


In [71]:
print(vector)

[23 28 35 12 12 12 48 35  7 34 42 39 17 19 22 12  2  5 42 33  9 34 31 42
 33]


In [72]:
v0 = vector[3:7]
print(v0)

[12 12 12 48]


In [73]:
v0[:] = 99

In [74]:
print(v0)

[99 99 99 99]


In [75]:
print(vector)

[23 28 35 99 99 99 99 35  7 34 42 39 17 19 22 12  2  5 42 33  9 34 31 42
 33]


In [76]:
# if that's not desired, make a copy first
v1 = vector[3:7].copy()
print(v1)

[99 99 99 99]


In [77]:
v1[:] = 0
print(v1)

[0 0 0 0]


In [78]:
print(vector)

[23 28 35 99 99 99 99 35  7 34 42 39 17 19 22 12  2  5 42 33  9 34 31 42
 33]


In [79]:
matrix = np.array(range(1,10)).reshape((3,3))
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
matrix[0][0]

1

In [81]:
matrix[0,0]

1

In [82]:
matrix[1][0]

4

In [83]:
# numpy uses row-major indexing
row = 1; col = 0
matrix[row][col]

4

In [84]:
# grab a specific row
matrix[row,:]


array([4, 5, 6])

In [85]:
# grab a specific column
matrix[:,col]

array([1, 4, 7])

In [86]:
# grab columns 1 and over
matrix[:,col:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
col=1
matrix[:,col:]

array([[2, 3],
       [5, 6],
       [8, 9]])