In [1]:
# Agenda:
# 0. Thanksgiving break
#   - Class on Tuesday ( 11/22 )
#   - *** NO *** class on Thursday ( 11/24 )
# 1. Finish discussion of NumPy
# 2. Begin discussion of Pandas


In [2]:
# Last time:
# Vectors (1D arrays) and Matrices (2D arrays)
# Conversion from lists
# np.arange() vs. range()
# linspace() --- handy for plotting
# various useful/utility routines for creating arrays:
#  np.zeros(), np.ones(), np.eye(), np.empty()
# Using NumPy for random number generation
# Indexing arrays --- slicing syntax
# --- 2 options for 2D arrays
# --- a[0][1] or a[0,1]
# Using slicing to "broadcast" values/assignments
# slicing "in-place" (default) vs. copy()


In [3]:
# Conditional selection (i.e. filtering numpy arrays)
import numpy as np
v = np.arange(10)
# select values greater than 2
gt2 = v > 2 # applies the condition
# less than 8
lt8 = v < 8

print(v)
# gt2 and lt8 are vectors of boolean values
# --- True if condition is met, False otherwise
print(gt2)
print(lt8)

[0 1 2 3 4 5 6 7 8 9]
[False False False  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False False]


In [4]:
print(v[gt2]) # filter the data

[3 4 5 6 7 8 9]


In [5]:
print(v[lt8])

[0 1 2 3 4 5 6 7]


In [6]:
# not necessary to story the condition as a variable
print(v[v<8])

[0 1 2 3 4 5 6 7]


In [8]:
# chain together conditions
print(v[(v > 2) & (v < 7)])

[3 4 5 6]


In [9]:
print(v[(v > 7) | (v < 2)])

[0 1 8 9]


In [10]:
print(v[v==5])

[5]


In [11]:
print(v[v!=5])

[0 1 2 3 4 6 7 8 9]


In [12]:
# Math operations
# The usual
# +, -, *, /
v = v + (2 * v)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [13]:
print(v / v)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [14]:
# One way to guard against divide by zero errors:
# add a small epsilon to the denominator
print(v / ( v + 0.001))

[0.         0.99966678 0.99983336 0.9998889  0.99991667 0.99993334
 0.99994445 0.99995238 0.99995834 0.99996296]


In [15]:
# Applies to scalars as well:
print(v * 10)

[  0  30  60  90 120 150 180 210 240 270]


In [16]:
print(np.sqrt(v))

[0.         1.73205081 2.44948974 3.         3.46410162 3.87298335
 4.24264069 4.58257569 4.89897949 5.19615242]


In [17]:
# number of elements that are less than 5
sum(v < 5)

2

In [18]:
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [19]:
# the sume of the all elements that are less than 5
sum(v[v < 5])

3

In [21]:
import math # use pi
radians = np.arange(1,11)*math.pi


In [22]:
print(radians)

[ 3.14159265  6.28318531  9.42477796 12.56637061 15.70796327 18.84955592
 21.99114858 25.13274123 28.27433388 31.41592654]


In [23]:
np.sin(radians)

array([ 1.22464680e-16, -2.44929360e-16,  3.67394040e-16, -4.89858720e-16,
        6.12323400e-16, -7.34788079e-16,  8.57252759e-16, -9.79717439e-16,
        1.10218212e-15, -1.22464680e-15])

In [24]:
# the above is kind of boring. Let's create a vector that steps 
# by pi/4
radians = np.arange(0,math.pi+math.pi/4,math.pi/4)

In [25]:
print(radians)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [26]:
print(np.sin(radians))

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


In [27]:
print(np.cos(radians))

[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


In [28]:
# Apply to matrices
m = np.random.rand(5,5)
print(m)


[[0.01195549 0.17932881 0.70042748 0.09120582 0.22948016]
 [0.84657379 0.77715829 0.29055088 0.6873759  0.12266489]
 [0.92589731 0.81787682 0.86306183 0.58530223 0.78910631]
 [0.32955425 0.58006332 0.4701234  0.79998527 0.87364068]
 [0.49373307 0.20438425 0.05661211 0.09968121 0.46486275]]


In [30]:
np.floor(m*1000)

array([[ 11., 179., 700.,  91., 229.],
       [846., 777., 290., 687., 122.],
       [925., 817., 863., 585., 789.],
       [329., 580., 470., 799., 873.],
       [493., 204.,  56.,  99., 464.]])

In [31]:
np.round(m*1000)

array([[ 12., 179., 700.,  91., 229.],
       [847., 777., 291., 687., 123.],
       [926., 818., 863., 585., 789.],
       [330., 580., 470., 800., 874.],
       [494., 204.,  57., 100., 465.]])

In [32]:
np.ceil(m*1000)

array([[ 12., 180., 701.,  92., 230.],
       [847., 778., 291., 688., 123.],
       [926., 818., 864., 586., 790.],
       [330., 581., 471., 800., 874.],
       [494., 205.,  57., 100., 465.]])

In [33]:
m.sum()

12.29060632967073

In [34]:
# to sum each row, use axis=1
m.sum(axis=1)

array([1.21239776, 2.72432375, 3.9812445 , 3.05336692, 1.3192734 ])

In [35]:
# to sum each column, use axis=0
m.sum(axis=0)

array([2.60771392, 2.55881149, 2.3807757 , 2.26355042, 2.47975479])

In [36]:
# the axis concept applies to other math operations
# min value in each row
m.min(axis=1)

array([0.01195549, 0.12266489, 0.58530223, 0.32955425, 0.05661211])

In [40]:
print(m)

[[0.01195549 0.17932881 0.70042748 0.09120582 0.22948016]
 [0.84657379 0.77715829 0.29055088 0.6873759  0.12266489]
 [0.92589731 0.81787682 0.86306183 0.58530223 0.78910631]
 [0.32955425 0.58006332 0.4701234  0.79998527 0.87364068]
 [0.49373307 0.20438425 0.05661211 0.09968121 0.46486275]]


In [38]:
# min value in each column
m.min(axis=0)

array([0.01195549, 0.17932881, 0.05661211, 0.09120582, 0.12266489])

In [39]:
m.cumsum()

array([1.19554882e-02, 1.91284298e-01, 8.91711781e-01, 9.82917604e-01,
       1.21239776e+00, 2.05897155e+00, 2.83612984e+00, 3.12668072e+00,
       3.81405662e+00, 3.93672151e+00, 4.86261883e+00, 5.68049565e+00,
       6.54355748e+00, 7.12885970e+00, 7.91796601e+00, 8.24752027e+00,
       8.82758359e+00, 9.29770699e+00, 1.00976923e+01, 1.09713329e+01,
       1.14650660e+01, 1.16694503e+01, 1.17260624e+01, 1.18257436e+01,
       1.22906063e+01])

In [41]:
m.cumprod()

array([1.19554882e-02, 2.14396347e-03, 1.50169094e-03, 1.36962957e-04,
       3.14302808e-05, 2.66080520e-05, 2.06786681e-05, 6.00820519e-06,
       4.12989546e-06, 5.06593187e-07, 4.69053271e-07, 3.83627799e-07,
       3.31094510e-07, 1.93790354e-07, 1.52921191e-07, 5.03958286e-08,
       2.92327718e-08, 1.37430100e-08, 1.09942055e-08, 9.60498521e-09,
       4.74229887e-09, 9.69251189e-10, 5.48713583e-11, 5.46964318e-12,
       2.54263339e-12])

In [42]:
# use np.unique() to filter out unique values
u = np.array([1,2,3]*3).reshape(3,3)

In [43]:
print(u)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
np.unique(u)

array([1, 2, 3])

In [45]:
u.reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [46]:
import pandas as pd

patients = {"name"  :["John Doe", "Sara Good", "Mary Jones"],
            "age"   :[44, 32, 75],
            "height":[72, 66, 60],
            "weight":[192, 140, 110],
            "smoker":[True, False, False]}
            
df = pd.DataFrame(data=patients)
print(df)

         name  age  height  weight  smoker
0    John Doe   44      72     192    True
1   Sara Good   32      66     140   False
2  Mary Jones   75      60     110   False


In [47]:
# filter operations are straightforward
# lets grab all of the patients who smoke
smokers = df[df['smoker'] == True]

In [48]:
print(smokers)

       name  age  height  weight  smoker
0  John Doe   44      72     192    True


In [49]:
under_40 = df[df["age"] < 40]

In [50]:
print(under_40)

        name  age  height  weight  smoker
1  Sara Good   32      66     140   False


In [52]:
vulnerable = df[ ( df["smoker"] == True ) & ( df["age"] > 40 ) ]

In [53]:
print(vulnerable)

       name  age  height  weight  smoker
0  John Doe   44      72     192    True


In [54]:
print(df[(df["smoker"] == True) | (df["age"] >= 65)])

         name  age  height  weight  smoker
0    John Doe   44      72     192    True
2  Mary Jones   75      60     110   False


In [55]:
print(df)

         name  age  height  weight  smoker
0    John Doe   44      72     192    True
1   Sara Good   32      66     140   False
2  Mary Jones   75      60     110   False


In [56]:
# filtering columns using key (field name) lists
print(df[["name","age"]])

         name  age
0    John Doe   44
1   Sara Good   32
2  Mary Jones   75


In [57]:
# adjust a column (e.g convert units)
df["height"] = df["height"]*0.0254
df["weight"] = df["weight"]*0.453592
print(df)


         name  age  height     weight  smoker
0    John Doe   44  1.8288  87.089664    True
1   Sara Good   32  1.6764  63.502880   False
2  Mary Jones   75  1.5240  49.895120   False


In [58]:
# add a column by referencing a new field that isn't already in the dataframe
df["bmi"] =  df["weight"]/(df["height"]*df["height"])

In [59]:
print(df)

         name  age  height     weight  smoker        bmi
0    John Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   32  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120   False  21.482664


In [60]:
# To edit individual cells, use "loc"
df.loc[0,"name"] = "Jon Doe"

In [61]:
print(df)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   32  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120   False  21.482664


In [62]:
df.loc[1,"age"] = 82

In [63]:
print(df)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   82  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120   False  21.482664


In [64]:
# use iloc[row,col] for purely numerical indexing
df.iloc[2, 4] = True

In [65]:
print(df)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   82  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120    True  21.482664


In [66]:
# Pandas has robus statistical operations
# For example, summarize selected numerical columns
print(df[["age","bmi"]].describe())

             age        bmi
count   3.000000   3.000000
mean   67.000000  23.372866
std    20.223748   2.375635
min    44.000000  21.482664
25%    59.500000  22.039502
50%    75.000000  22.596341
75%    78.500000  24.317967
max    82.000000  26.039593


In [67]:
df_sorted = df.sort_values([ "bmi", "age" ], axis = 0, ascending = True )

In [68]:
print(df)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   82  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120    True  21.482664


In [69]:
print(df_sorted)

         name  age  height     weight  smoker        bmi
2  Mary Jones   75  1.5240  49.895120    True  21.482664
1   Sara Good   82  1.6764  63.502880   False  22.596341
0     Jon Doe   44  1.8288  87.089664    True  26.039593


In [70]:
df_sorted = df.sort_values([ "bmi", "age" ], axis = 0, ascending = False )

In [71]:
print(df_sorted)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   82  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120    True  21.482664


In [72]:
num_smokers = sum(df["smoker"] == True)

In [73]:
print(num_smokers)

2


In [75]:
# how to add a new row(s) of data?
# Use append()

# let's create another patient dataframe
more = {"name"  :["Brad Samson", "Klaus Volmer", "Pat Gupta"],
        "age"   :[54, 27, 19],
        "height":[74, 63, 54],
        "weight":[215, 130, 125],
        "smoker":[False, False, True]}
df_more = pd.DataFrame(data = more)

In [76]:
# before we can append we need to add the "bmi" column
# unit conversions
df_more["height"] = df_more["height"]*0.0254
df_more["weight"] = df_more["weight"]*0.453592
df_more["bmi"]    = df_more["weight"]/(df_more["height"]*df_more["height"])

In [77]:
print(df)

         name  age  height     weight  smoker        bmi
0     Jon Doe   44  1.8288  87.089664    True  26.039593
1   Sara Good   82  1.6764  63.502880   False  22.596341
2  Mary Jones   75  1.5240  49.895120    True  21.482664


In [78]:
print(df_more)

           name  age  height    weight  smoker        bmi
0   Brad Samson   54  1.8796  97.52228   False  27.604061
1  Klaus Volmer   27  1.6002  58.96696   False  23.028211
2     Pat Gupta   19  1.3716  56.69900    True  30.138418


In [79]:
df = df.append(df_more, ignore_index = True)

In [80]:
print(df)

           name  age  height     weight  smoker        bmi
0       Jon Doe   44  1.8288  87.089664    True  26.039593
1     Sara Good   82  1.6764  63.502880   False  22.596341
2    Mary Jones   75  1.5240  49.895120    True  21.482664
3   Brad Samson   54  1.8796  97.522280   False  27.604061
4  Klaus Volmer   27  1.6002  58.966960   False  23.028211
5     Pat Gupta   19  1.3716  56.699000    True  30.138418
